package lu.kbra.gamebox.client.es.engine.utils.consts;

import org.lwjgl.opengles.GLES30;

public enum TextureParameter implements GLConstant {

	// DEPTH_STENCIL_MODE(GLES30.GL_DEPTH_STENCIL_TEXTURE_MODE),
	BASE_LEVEL(GLES30.GL_TEXTURE_BASE_LEVEL),

	// Compare
	COMPARE_FUNC(GLES30.GL_TEXTURE_COMPARE_FUNC), COMPARE_MODE(GLES30.GL_TEXTURE_COMPARE_MODE),

	// Interpolation filters
	MIN_FILTER(GLES30.GL_TEXTURE_MIN_FILTER), MAG_FILTER(GLES30.GL_TEXTURE_MAG_FILTER),

	// Lod
	MIN_LOD(GLES30.GL_TEXTURE_MIN_LOD), MAX_LOD(GLES30.GL_TEXTURE_MAX_LOD),

	MAX_LEVEL(GLES30.GL_TEXTURE_MAX_LEVEL),

	// Swizzle
	SWIZZLE_R(GLES30.GL_TEXTURE_SWIZZLE_R), SWIZZLE_G(GLES30.GL_TEXTURE_SWIZZLE_G), SWIZZLE_B(GLES30.GL_TEXTURE_SWIZZLE_B), SWIZZLE_A(GLES30.GL_TEXTURE_SWIZZLE_A),

	// Wrap
	WRAP_S(GLES30.GL_TEXTURE_WRAP_S), WRAP_T(GLES30.GL_TEXTURE_WRAP_T), WRAP_R(GLES30.GL_TEXTURE_WRAP_R), WRAP_VERTICAL(GLES30.GL_TEXTURE_WRAP_T), WRAP_HORIZONTAL(GLES30.GL_TEXTURE_WRAP_S), WRAP_DEPTH(GLES30.GL_TEXTURE_WRAP_R);

	private int glId;

	private TextureParameter(int id) {
		this.glId = id;
	}

	@Override
	public int getGlId() {
		return glId;
	}

}
