package lu.pcy113.pdr.engine.utils.consts;

import org.lwjgl.opengl.GL40;

public enum TexelFormat implements GLConstant {

	RED(GL40.GL_RED), GREEN(GL40.GL_GREEN), BLUE(GL40.GL_BLUE), ALPHA(GL40.GL_ALPHA),
	RG(GL40.GL_RG), RGB(GL40.GL_RGB), RGBA(GL40.GL_RGBA), BGR(GL40.GL_BGR), BGRA(GL40.GL_BGRA),
	RED_INTEGER(GL40.GL_RGB_INTEGER), GREEN_INTEGER(GL40.GL_GREEN_INTEGER), BLUE_INTEGER(GL40.GL_BLUE_INTEGER), ALPHA_INTEGER(GL40.GL_ALPHA_INTEGER),
	RG_iNTEGER(GL40.GL_RG_INTEGER), RGB_INTEGER(GL40.GL_RGB_INTEGER), RGBA_INTEGER(GL40.GL_RGBA_INTEGER), BGR_INTEGER, BGRA_INTEGER(GL40.GL_BGR_INTEGER),
	STENCIL_INDEX(GL40.GL_STENCIL_INDEX), DEPTH_COMPONENT(GL40.GL_DEPTH_COMPONENT), DEPTH_STENCIL(GL40.GL_DEPTH_STENCIL);

	private int glId;

	private TexelFormat(int id) {
		this.glId = id;
	}

	@Override
	public int getGlId() {
		return glId;
	}

}
